version: '3.9'

services:
  db:
    image: mariadb:10.5
    container_name: moodle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodleroot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: bitnami/moodle:4
    container_name: moodle_app
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: adminpass
    volumes:
      - moodle_data:/bitnami/moodle

volumes:
  db_data:
  moodle_data: